options(repos = c(CRAN="https://cloud.r-project.org"))
install.packages("stargazer")
install.packages("gplots")
install.packages("plm")
# install.packages("rmarkdown")
# install.packages("bookdown")
# install.packages("xfun")
# install.packages("tinytex")